proto/cheby/data/main_template.tex
proto/cheby/print_html.py
proto/cheby/print_latex.py
testfiles/features/semver1.html
testfiles/features/semver1.tex
testfiles/issue67/repeatInRepeat.html
testfiles/issue67/repeatInRepeat.tex
testfiles/issue84/sps200CavityControl_as.html
testfiles/issue84/sps200CavityControl_as.tex
testfiles/issue9/test.html
testfiles/issue9/test.tex

This PR improves the LaTeX documentation layout and was done in consultation with @stefanlippuner. 
- Add register `description` after register summary if register contains fields/children.
+ Single newline are respected (by adding `\\`).
+ Multiple newline are left and treated by LaTeX as a new paragraph.
- Allow line breaks inside bit field `description`.
+ Each newline is simply replaced with a `\newline` command (similar behavior than `\\`).
- Remove the `access` column from the bit field table to gain more width for the `description` column.
+ Not necessary to state per bit field as `access` type is set per register.
+ Add `access` type to the register summary instead.
- Allow bit field table to break at page end and spread over multiple pages.
- Adapt long table layout.
+ Remove …

LaTeX updates and consistent newline support in documentation

---

proto/cheby/gen_c.py
proto/tests.py
testfiles/padding-block/reg.cheby

Changes:
- Fix crash in maybe_pad due to missing el.
- Add small testcase for this crash.
- Change padding comment from words to bytes, as the 'words' could have a different width in the same file.
On master, generating a C file for the test file results in the following crash in `maybe_pad`:
```bash
cheby-dev -i reg.cheby --gen-c reg.h
File "proto/cheby/tree.py", line 32, in visit
return f(*args, **kwargs)
File "proto/cheby/gen_c.py", line 125, in cprint_block
cprint_children(cp, n, n.c_size)
File "proto/cheby/gen_c.py", line 100, in cprint_children
maybe_pad(size - addr)
File "proto/cheby/gen_c.py", line 69, in maybe_pad
cp.cp_txt('/* padding to: {} words */'.format(el.c_address // sz))
NameError: free variable 'el' referenced before assignment in enclosing scope
```
The bug is …

Fix crash in maybe_pad due to missing el, make parameters explicit

---

.github/workflows/ci.yml
testfiles/tb/run.sh

This enables the Gitlab CI jobs on Github too. This should hopefully prevent us from merging broken commits.
I had to switch `/testfiles/tb/run.sh` to bash, because /bin/sh doesn't point to bash on Ubuntu (the only Linux availbe for Github actions).
Example pipeline: https://github.com/stefanlippuner/cheby/actions/runs/6271367017

Add CI configuration for Github (on push / pull request)

---

proto/cheby/print_latex.py

Add support for equations in LaTeX documentation by not escaping strings between `$` ... `$`.

Equations in LaTeX documentation

---

doc/cheby-ug.txt
proto/cheby/expand_hdl.py
proto/cheby/hdl/genreg.py
proto/tests.py
testfiles/features/no_port.cheby
testfiles/features/no_port.vhdl

Add a new `x-hdl.type` `no-port`: Such register act like a small memory element having no input or output port.

No port register type

---

doc/cheby-ug.txt
proto/cheby/expand_hdl.py
proto/cheby/hdl/genreg.py
proto/cheby/layout.py
testfiles/tb/run.sh
testfiles/tb/wmask.cheby

Originally introduced in d8c313276e086175e5a37b0ea0a8d0825b946bb1 (as part of #16), the hard-coded constant is replaced with a `x-hdl` attribute to be set on the memory map.

Add x-hdl attribute to control write mask generation

---

proto/cheby/print_vhdl.py
testfiles/features/no_port.cheby
testfiles/features/no_port.sv
testfiles/features/no_port.vhdl

If all registers in a memory map are of type `no-port`, the entity does not have any ports besides the interface ports. Since in VHDL, the interface ports are always generated with a `;`, the entity then has a trailing semicolon:
```vhdl
...
prdata               : out   std_logic_vector(31 downto 0);
pslverr              : out   std_logic;
);
end no_port;
```
instead of (see after `std_logic`):
```vhdl
...
prdata               : out   std_logic_vector(31 downto 0);
pslverr              : out   std_logic
);
end no_port;
```
This fix introduces an IO buffer in Python to which all strings are written first. Then, the very last semicolon gets removed before the buffer is written into the output file. Also, the `no_port` testcase is updated to verify this new behavior.

Fix trailing semicolon for VHDL entities without ports

---

proto/cheby/hdl/genreg.py
testfiles/tb/golden_files/wmask_apb.vhdl
testfiles/tb/golden_files/wmask_avalon.vhdl
testfiles/tb/golden_files/wmask_axi4.vhdl
testfiles/tb/golden_files/wmask_wb.vhdl
testfiles/tb/wmask.cheby
testfiles/tb/wmask_apb_tb.vhdl
testfiles/tb/wmask_avalon_tb.vhdl
testfiles/tb/wmask_axi4_tb.vhdl
testfiles/tb/wmask_wb_tb.vhdl

Write masks were added in #16. Similar code between register fields and wire fields was used. Since register fields are assigned in a sequential process, using the same signal name on the right side of the assignment (i.e., the current value) and on the left side (i.e. the new value) is permitted. This is not valid for wires where such a code creates an infinite loop. Instead, when using write masks with read-write wire fields, the input wire value has to be used on the right side of the assignment (i.e., the current value), while the output wire value has to be used on the left side (i.e. the new value).
I.e., having the following cheby file:
```yaml
memory-map:
...
x-hdl:
wmask: True
children:
...
- reg:
name: wire_rw
type: unsigned
width: 32
access: rw
preset: 0x00000000
x-hdl:
type: …
```

Add separate write mask port for (read-)write wire fields

---

doc/cheby-ug.txt

Just a small documentation follow-up on https://github.com/tgingold-cern/cheby/pull/19.

Doc - Add a short note on newlines in the description field

---

proto/cheby/print_latex.py

Hey Tristan :)
This PR just fixes some small bugs with the Latex escaping (`\~`, `\^` are not valid).

Latex - Fix escaping of special chars (tilde, circumflex)

---

proto/cheby/print_consts.py

Bug introduced in #43:
If there is a register containing a single field and both share the same name, both of their `c_name`s will be equal. Hence, when the default separator `_` is selected, `pr_name()` will return the same name for the register as well as for the field. Printing the address for the register and the field will therefore lead to the same constant printed twice.
E.g.
```yaml
- reg:
name: foo_bar
description: 'Foo Bar'
width: 32
access: rw
children:
- field:
name: foo_bar
description: 'Foo Bar'
range: 31-0
- reg:
...
```
will lead to the following VHDL constant generation (`ADDR_REG_SET_FOO_BAR` declared twice):
```vhdl
constant ADDR_REG_SET_FOO_BAR : Natural := 16#c#;
constant ADDR_REG_SET_FOO_BAR : Natural := 16#c#;
constant REG_SET_FOO_BAR_OFFSET : Natural := 0;
``` …

Fix constants generation with same c_name between register and field

---

proto/cheby/hdl/genreg.py

When using a write mask, fields are normally updated like following
```
new_data = (old_data and !write_mask) or (write_data and write_mask)
```
Since in the case of the autoclear field, the previous data is irrelevant it should not be ORed:
```
new_data = write_data and write_mask
```
Otherwise, two consecutive write requests to the same register with different masks might keep the field asserted.

Do not OR autoclear fields with previous value

---

proto/cheby/expand_hdl.py
proto/cheby/hdl/genreg.py
testfiles/issue59/inherit.sv
testfiles/issue59/inherit.v
testfiles/issue59/inherit.vhdl
testfiles/tb/golden_files/reg4wrw_wb.vhdl

The write strobe should be asserted synchronously with the update of the register/field in case of a write request. Since the register has to first sample the write data, the write strobe is a delay version of the write request.
In case of a register or field of type "wire" this is no longer true: There is no register and as such the write data is directly forwarded to the output ports. Hence, the write strobe also should be forwarded without prior sampling. In case where a register contains fields with multiple different types, two write strobes are generated: One delayed as before and a new one for the fields of type "wire" that is directly forwarded.

Align write strobe in case of register/field of type "wire"

---

proto/cheby/gen_c.py
proto/tests.py
testfiles/features/blkprefix3.h

:wave: 
This is a small change to adapt the C struct output to match the other outputs more closely in case `block-prefix: False` is defined for a block. E.g. The C defines for the register address already omit the name of the block in this case.
It turns this output
```c
#ifndef __ASSEMBLER__
struct my_reg {
/* [0x4]: BLOCK Interrupt registers */
struct irq_regs {
/* [0x0]: REG (ro) Interrupt status. */
uint32_t irq_status;
/* [0x4]: REG (rw) Interrupt enable. */
uint32_t irq_enable;
} irq_regs;
```
into this:
```c
#ifndef __ASSEMBLER__
struct my_reg {
/* [0x4]: BLOCK Interrupt registers */
/* [0x0]: REG (ro) Interrupt status. */
uint32_t irq_status;
/* [0x4]: REG (rw) Interrupt enable. */
uint32_t irq_enable;
```
Let me know if I should add a testcase for this.

C - Omit struct in hierarchy for blocks with block-prefix: False

---

proto/cheby/gen_c.py
proto/tests.py
testfiles/features/blkprefix5.cheby
testfiles/features/blkprefix5.h
testfiles/features/blkprefix5.sv
testfiles/features/blkprefix5.v
testfiles/features/blkprefix5.vhdl

With the change from #55, I've introduced/triggered a new issue :| If padding is inserted at the top-level and within a block omitted prefix, the same name is given to the padding variable resulting in compilation errors, e.g.
```c
#ifndef __ASSEMBLER__
struct blkprefix3 {
/* [0x0]: BLOCK (comment missing) */
/* [0x0]: REG (rw) (comment missing) */
uint32_t r1;
/* padding to: 8 Bytes */
uint32_t __padding_0[1];
/* [0x8]: REG (rw) (comment missing) */
uint64_t r2;
/* [0x10]: BLOCK (comment missing) */
/* [0x0]: REG (rw) (comment missing) */
uint32_t r3;
/* padding to: 8 Bytes */
uint32_t __padding_0[1];
/* [0x8]: REG (rw) (comment missing) */
uint64_t r4;
/* [0x20]: BLOCK (comment missing) */
struct b2 {
/* [0x0]: REG (rw) (comment missing) */
uint32_t r1;
/* padding to: 8 Bytes */ …
```

 C - Fix padding numbering when structs are omitted 

---

proto/cheby/main.py
proto/cheby/print_html.py

Adapts the HTML documentation generation:
-  Replace any strings inside the description/comment fields wrapped by dollar signs (`$` and `$`) indicating a LaTeX equation with inline delimiters (`\(` and `\)`) such that the equations can be detected by [MathJax](https://docs.mathjax.org/en/latest/basic/mathematics.html).
- Adds new argument `--doc-include-js-dep` to allow insertion of external JavaScript dependencies:
```html
...
</STYLE>
<script type="text/javascript" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"></script>
</HEAD>
...
```
Renders inline equations such as `$f_s = \frac{30.72}{2} \text{MHz}$` as Matlab equations $f_s = \frac{30.72}{2} \text{MHz}$.

LaTeX equation rendering in HTML documentation

---

proto/cheby/gen_c.py
proto/cheby/print_consts.py
testfiles/bug-gen-c-02/fip_urv_regs.h
testfiles/bug-gen-c-02/mbox_regs.h
testfiles/bug-same-label/same_label.h
testfiles/features/blkprefix3.h
testfiles/features/blkprefix5.h
testfiles/issue103/top.h
testfiles/issue67/repeatInRepeat.h
testfiles/issue67/repeatInRepeatC.h

With the changes from #61, descriptions were removed from being printed in the code. If the field contains no comment, the string `(missing comment)` gets printed. Having very little comments in our cheby maps, we have now the `(missing comment)` all over without adding much information to the code.
This pull request improves #61 by printing the name of the field if no comment is present or skipping to print anything altogether. See the regenerated testfiles for a comparison.

Remove empty comments from code

---

proto/cheby/hdl/axi4litebus.py
proto/cheby/hdl/wbbus.py
testfiles/issue143/map-consts.sv
testfiles/issue143/map-consts.vhdl
testfiles/mr67/top-consts.sv
testfiles/mr67/top-consts.vhdl

- Add correct typing constraints for older Python versions
* (`Dict` from `typing` package instead of `dict` to support Python < 3.9)
- Remove unused package imports in code
- Fix some VHDL packaging names (to match with the generated version)

Smaller fixes

---

proto/cheby/main.py
proto/cheby/print_markdown.py
testfiles/features/semver1.md
testfiles/issue67/repeatInRepeat.md
testfiles/issue84/sps200CavityControl_as.md
testfiles/issue9/test.md

The overall goal of this PR is to improve the Markdown documentation generation such that it can easily be displayed in GitLab and GitHub. Since some of the tables in the Markdown documentation are generated based on AsciiDoc, GitLab and GitHub failed to display them properly. Overall, the following points have been addressed:
- Match Markdown output to LaTeX documentation
- Generate HTML tables instead of AsciiDoc tables for register drawings (showing which bit field is placed where in the register)

Match Markdown to LaTeX documentation

---

proto/cheby/print_consts.py

Currently, there are two types of constant files that can be generated in `proto/cheby/print_consts.py`:
- `ConstsVisitor`
- `StructVisitor`
For the later, each bit field is generated as a structure linked to its parent elements, e.g. in Matlab we get for a single field:
```matlab
REG_TOP.status.idle.WIDTH = 1;
REG_TOP.status.idle.OFFSET = 0;
REG_TOP.status.idle.WIDTH = 1;
```
For any entry that is not a bit field such as submaps, no structure or constant is generated. This is particularly a problem when using nested register maps. This PR proposes now to include as the very least the address for submaps, e.g.
```matlab
REG_TOP.submap.ADDR = 256;
```

Print addresses for submaps in struct constant files
